const { interpolateValue } = require('./templateRenderer');

function getDefaultFooterLinks(vars = {}) {
  return [
    { label: 'Website', url: vars.website_url },
    { label: 'Contact', url: `mailto:${vars.support_email}` },
    { label: 'Privacy Policy', url: vars.privacy_url },
    { label: 'Terms', url: vars.terms_url },
  ];
}

function createTemplate(definition) {
  return (variables = {}) => ({
    ...interpolateValue(definition, variables),
    footerLinks: getDefaultFooterLinks(variables),
  });
}

const templates = {
  welcome_email: createTemplate({
    statusLabel: 'Welcome',
    subject: 'Welcome to ChatorAI, {{user_name}}',
    preheader: 'Your workspace is ready for setup.',
    title: 'Your workspace is ready',
    intro: 'Welcome to ChatorAI. Your account has been created and your team can start setup immediately.',
    sections: [
      'You can finish the initial setup in under five minutes by connecting your first channel and reviewing your AI onboarding profile.',
      'Once that is done, your workspace will be ready for live conversations, reporting, and handoff workflows.',
    ],
    cta: { label: 'Complete Setup', url: '{{setup_link}}' },
    supportTitle: 'Need help?',
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'Your workspace was created for {{workspace_name}}.',
    footerNote: 'ChatorAI transactional notification',
  }),
  email_verification: createTemplate({
    statusLabel: 'Verify Email',
    subject: 'Verify your ChatorAI email address',
    preheader: 'Confirm your email to secure your account.',
    title: 'Confirm your email address',
    intro: 'Use the button below to verify the email address connected to your ChatorAI account.',
    sections: [
      'Verifying your email keeps account recovery, invitations, and billing notifications pointed to the right person.',
    ],
    cta: { label: 'Verify Email', url: '{{verification_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'If you did not create this account, you can safely ignore this email.',
    footerNote: 'Verification links are one-time use.',
  }),
  password_reset: createTemplate({
    statusLabel: 'Security',
    subject: 'Reset your ChatorAI password',
    preheader: 'Use this secure link to reset your password.',
    title: 'Reset your password',
    intro: 'We received a request to reset the password for your ChatorAI account.',
    sections: [
      'Use the secure link below to choose a new password.',
      'For your security, this link expires in {{expiry_minutes}} minutes and can only be used once.',
    ],
    cta: { label: 'Reset Password', url: '{{reset_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'If you did not request this reset, you can safely ignore this email.',
    footerNote: 'This is a security notification from ChatorAI.',
  }),
  password_changed_alert: createTemplate({
    statusLabel: 'Security',
    subject: 'Your ChatorAI password was changed',
    preheader: 'Your account credentials were updated.',
    title: 'Your password has been updated',
    intro: 'The password for your ChatorAI account was changed successfully.',
    sections: [
      'If you made this change, no further action is needed.',
      'If you did not make this change, reset your password immediately and contact support.',
    ],
    cta: { label: 'Secure Account', url: '{{security_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'This alert was generated automatically for account protection.',
    footerNote: 'Security event recorded for {{workspace_name}}.',
  }),
  team_invitation: createTemplate({
    statusLabel: 'Team Invitation',
    subject: '{{inviter_name}} invited you to join {{workspace_name}}',
    preheader: 'Join your ChatorAI workspace.',
    title: 'You have been invited to ChatorAI',
    intro: '{{inviter_name}} invited you to join the {{workspace_name}} workspace as {{role_name}}.',
    sections: [
      'Use the link below to accept the invitation, set your password, and access the workspace.',
      'This invitation is one-time use and expires on {{invite_expiry}}.',
    ],
    cta: { label: 'Join Workspace', url: '{{invite_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'If you were not expecting this invitation, you can ignore this email.',
    footerNote: 'Invitation sent from ChatorAI.',
  }),
  demo_submission_confirmation: createTemplate({
    statusLabel: 'Demo Confirmed',
    subject: 'Your ChatorAI demo request has been received',
    preheader: 'Your team will hear from us shortly.',
    title: 'Your demo request is confirmed',
    intro: 'We received your request and our team is preparing a tailored walkthrough for {{company_name}}.',
    sections: [
      'We will contact you using the details you submitted to confirm the best time and agenda.',
      'Your session will focus on the channels, workflows, and revenue goals most relevant to your team.',
    ],
    cta: { label: 'View Demo Details', url: '{{demo_details_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'If you need to reschedule, use the details page linked above.',
    footerNote: 'Demo operations notification from ChatorAI.',
  }),
  demo_internal_notification: createTemplate({
    statusLabel: 'Sales Alert',
    subject: 'New ChatorAI demo request from {{company_name}}',
    preheader: 'A new demo request needs follow-up.',
    title: 'New demo request',
    intro: '{{user_name}} from {{company_name}} requested a ChatorAI demo.',
    sections: [
      'Team size: {{team_size}}.',
      'Email: {{user_email}}. Phone: {{phone_display}}.',
      'Comments: {{comments_display}}',
      'Use the request record to coordinate scheduling and follow-up.',
    ],
    cta: { label: 'Open Demo Request', url: '{{admin_demo_link}}' },
    supportText: 'This notification was sent to the configured revenue operations recipients.',
    trustText: 'No request should remain unassigned.',
    footerNote: 'Revenue operations alert.',
  }),
  trial_started: createTemplate({
    statusLabel: 'Trial Started',
    subject: 'Your ChatorAI trial is live',
    preheader: 'Your trial workspace is active now.',
    title: 'Your trial has started',
    intro: 'Your ChatorAI workspace is active and available through {{trial_end_date}}.',
    sections: [
      'Connect a channel, review your AI profile, and invite teammates to see the platform in real conditions.',
      'Your plan can be upgraded at any time without losing setup progress.',
    ],
    cta: { label: 'Open Workspace', url: '{{dashboard_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'Your trial window ends on {{trial_end_date}}.',
    footerNote: 'Trial lifecycle notification.',
  }),
  trial_ending_soon: createTemplate({
    statusLabel: 'Trial Ending',
    subject: 'Your ChatorAI trial ends on {{trial_end_date}}',
    preheader: 'Keep your setup and conversations active.',
    title: 'Your trial is about to end',
    intro: 'Your trial workspace will expire on {{trial_end_date}}.',
    sections: [
      'Upgrade now to keep your connected channels, configuration, and team access uninterrupted.',
      'If you need help choosing a plan, our team can review usage and next steps with you.',
    ],
    cta: { label: 'Upgrade Now', url: '{{upgrade_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'Your current setup remains available until the trial closes.',
    footerNote: 'Trial lifecycle notification.',
  }),
  trial_expired: createTemplate({
    statusLabel: 'Trial Expired',
    subject: 'Your ChatorAI trial has expired',
    preheader: 'Reactivate your workspace to keep moving.',
    title: 'Your trial has ended',
    intro: 'Your trial period has ended for {{workspace_name}}.',
    sections: [
      'Upgrade your workspace to restore live operations, billing notifications, and team access.',
      'Your setup history has been preserved so you can continue where you left off.',
    ],
    cta: { label: 'Reactivate Workspace', url: '{{upgrade_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'Your configuration remains available for reactivation.',
    footerNote: 'Trial lifecycle notification.',
  }),
  payment_success: createTemplate({
    statusLabel: 'Billing',
    subject: 'Payment received for {{workspace_name}}',
    preheader: 'Your subscription payment was successful.',
    title: 'Payment successful',
    intro: 'We received your payment and your ChatorAI subscription remains active.',
    sections: [
      'Plan: {{plan_name}}.',
      'Amount: {{billing_amount}} {{billing_currency}}.',
    ],
    cta: { label: 'View Invoice', url: '{{invoice_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'Your billing history is also available in the dashboard.',
    footerNote: 'Billing confirmation from ChatorAI.',
  }),
  payment_failed: createTemplate({
    statusLabel: 'Billing',
    subject: 'Payment failed for {{workspace_name}}',
    preheader: 'Update your payment method to avoid interruption.',
    title: 'Payment could not be processed',
    intro: 'We could not process the latest payment for your ChatorAI subscription.',
    sections: [
      'Update your payment method to keep your workspace active and avoid service interruption.',
      'We will retry according to your billing schedule.',
    ],
    cta: { label: 'Update Payment Method', url: '{{billing_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'If your payment details were updated recently, you can ignore this notice.',
    footerNote: 'Billing action required.',
  }),
  invoice_receipt: createTemplate({
    statusLabel: 'Receipt',
    subject: 'Invoice for {{workspace_name}}',
    preheader: 'Your ChatorAI invoice is ready.',
    title: 'Your invoice is ready',
    intro: 'A new invoice has been issued for {{workspace_name}}.',
    sections: [
      'Amount: {{billing_amount}} {{billing_currency}}.',
      'Invoice reference: {{invoice_number}}.',
    ],
    cta: { label: 'View Invoice', url: '{{invoice_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'Your invoice is also available in the billing dashboard.',
    footerNote: 'Billing document from ChatorAI.',
  }),
  subscription_renewal_notice: createTemplate({
    statusLabel: 'Renewal',
    subject: 'Upcoming renewal for {{workspace_name}}',
    preheader: 'Your subscription renews on {{renewal_date}}.',
    title: 'Your subscription renews soon',
    intro: 'Your ChatorAI subscription is scheduled to renew on {{renewal_date}}.',
    sections: [
      'Review billing details now if you need to update payment information or seat counts before renewal.',
    ],
    cta: { label: 'Review Billing', url: '{{billing_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'No action is required if your billing details are current.',
    footerNote: 'Subscription lifecycle notification.',
  }),
  cancellation_confirmation: createTemplate({
    statusLabel: 'Subscription',
    subject: 'Subscription canceled for {{workspace_name}}',
    preheader: 'Your subscription has been canceled.',
    title: 'Your subscription has been canceled',
    intro: 'We confirmed the cancellation for {{workspace_name}}.',
    sections: [
      'Your current access remains available until the end of the paid period, after which billing stops.',
      'Your data and setup remain available for reactivation under the platform retention policy.',
    ],
    cta: { label: 'Review Subscription', url: '{{billing_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'This notice confirms the change recorded on your billing profile.',
    footerNote: 'Subscription lifecycle notification.',
  }),
  connect_first_channel_reminder: createTemplate({
    statusLabel: 'Onboarding',
    subject: 'Connect your first channel in ChatorAI',
    preheader: 'Complete the first operational setup step.',
    title: 'Connect your first channel',
    intro: 'Your workspace is ready, but it does not have a live channel connected yet.',
    sections: [
      'Connect WhatsApp, Instagram, Messenger, or Live Chat to start handling real customer conversations.',
    ],
    cta: { label: 'Open Dashboard', url: '{{dashboard_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'The first connected channel unlocks reporting and automation value immediately.',
    footerNote: 'Onboarding reminder from ChatorAI.',
  }),
  no_activity_reminder: createTemplate({
    statusLabel: 'Engagement',
    subject: 'Activity is low in {{workspace_name}}',
    preheader: 'Your team has not been active recently.',
    title: 'Your workspace has been quiet',
    intro: 'We noticed limited recent activity in {{workspace_name}}.',
    sections: [
      'Review connected channels, recent conversations, and pending actions to keep the workspace operational.',
    ],
    cta: { label: 'Open Dashboard', url: '{{dashboard_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'This reminder is based on recent workspace activity.',
    footerNote: 'Lifecycle reminder from ChatorAI.',
  }),
  re_engagement_email: createTemplate({
    statusLabel: 'Re-engagement',
    subject: 'Bring {{workspace_name}} back into motion',
    preheader: 'Reconnect with your ChatorAI workspace.',
    title: 'Re-engage your workspace',
    intro: 'Your workspace has been inactive long enough that it may be drifting out of your operational flow.',
    sections: [
      'Reconnect channels, review AI performance, and restore team activity to keep lead handling and support workflows moving.',
    ],
    cta: { label: 'Return to Dashboard', url: '{{dashboard_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'All prior setup remains available.',
    footerNote: 'Lifecycle reminder from ChatorAI.',
  }),
  usage_limit_warning: createTemplate({
    statusLabel: 'Usage',
    subject: '{{metric_name}} usage is approaching the plan limit',
    preheader: 'Your workspace is nearing a plan threshold.',
    title: 'Usage limit warning',
    intro: '{{metric_name}} is at {{percent_used}}% of the current plan allowance.',
    sections: [
      'Review plan limits and upgrade before the workspace reaches capacity.',
      'Current plan: {{plan_name}}.',
    ],
    cta: { label: 'Review Plan', url: '{{billing_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'Usage is based on the current billing cycle.',
    footerNote: 'Usage notification from ChatorAI.',
  }),
  feature_adoption_reminder: createTemplate({
    statusLabel: 'Adoption',
    subject: 'Activate {{feature_name}} in {{workspace_name}}',
    preheader: 'A key workflow is still waiting to be enabled.',
    title: 'A high-value feature is still inactive',
    intro: '{{feature_name}} has not been configured yet in {{workspace_name}}.',
    sections: [
      'Completing this setup helps your team get full value from automation, reporting, and revenue workflows.',
    ],
    cta: { label: 'Open Dashboard', url: '{{dashboard_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'This reminder focuses on adoption of a core workflow.',
    footerNote: 'Product adoption reminder.',
  }),
  whatsapp_connected: createTemplate({
    statusLabel: 'Channel Connected',
    subject: 'WhatsApp connected to {{workspace_name}}',
    preheader: 'Your WhatsApp channel is active.',
    title: 'WhatsApp is connected',
    intro: 'Your WhatsApp channel is now connected and ready for live conversations.',
    sections: [
      'You can review credentials, routing, and response handling from the dashboard.',
    ],
    cta: { label: 'Open Dashboard', url: '{{dashboard_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'Operational channel status has been updated.',
    footerNote: 'Channel operations notification.',
  }),
  instagram_connected: createTemplate({
    statusLabel: 'Channel Connected',
    subject: 'Instagram connected to {{workspace_name}}',
    preheader: 'Your Instagram channel is active.',
    title: 'Instagram is connected',
    intro: 'Your Instagram channel is now connected and ready for live conversations.',
    sections: [
      'You can review credentials, routing, and response handling from the dashboard.',
    ],
    cta: { label: 'Open Dashboard', url: '{{dashboard_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'Operational channel status has been updated.',
    footerNote: 'Channel operations notification.',
  }),
  messenger_connected: createTemplate({
    statusLabel: 'Channel Connected',
    subject: 'Messenger connected to {{workspace_name}}',
    preheader: 'Your Messenger channel is active.',
    title: 'Messenger is connected',
    intro: 'Your Messenger channel is now connected and ready for live conversations.',
    sections: [
      'You can review credentials, routing, and response handling from the dashboard.',
    ],
    cta: { label: 'Open Dashboard', url: '{{dashboard_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'Operational channel status has been updated.',
    footerNote: 'Channel operations notification.',
  }),
  token_expired_alert: createTemplate({
    statusLabel: 'Channel Alert',
    subject: '{{channel_name}} token expired for {{workspace_name}}',
    preheader: 'A connected channel needs attention.',
    title: 'A channel token has expired',
    intro: '{{channel_name}} requires reconnection before message processing is interrupted.',
    sections: [
      'Reconnect the channel from the dashboard to restore normal operations.',
    ],
    cta: { label: 'Open Dashboard', url: '{{dashboard_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'This alert is generated when a channel credential is no longer valid.',
    footerNote: 'Channel operations notification.',
  }),
  webhook_failure_alert: createTemplate({
    statusLabel: 'Operational Alert',
    subject: 'Webhook delivery issue in {{workspace_name}}',
    preheader: 'An integration failure needs attention.',
    title: 'Webhook delivery failure detected',
    intro: 'A webhook failure was detected for {{workspace_name}}.',
    sections: [
      'Source: {{webhook_source}}.',
      'Error: {{error_summary}}.',
    ],
    cta: { label: 'Open Dashboard', url: '{{dashboard_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'This notice is sent to help preserve delivery reliability.',
    footerNote: 'System operations alert.',
  }),
  human_takeover_required: createTemplate({
    statusLabel: 'Escalation',
    subject: 'Human takeover required in {{workspace_name}}',
    preheader: 'A conversation needs immediate review.',
    title: 'Human takeover required',
    intro: 'A conversation has been escalated and needs human review.',
    sections: [
      'Customer: {{customer_name}}.',
      'Reason: {{handoff_reason}}.',
    ],
    cta: { label: 'Open Conversation', url: '{{conversation_link}}' },
    supportText: 'This alert was sent to workspace operators with elevated access.',
    trustText: 'The conversation remains pending until a teammate accepts it.',
    footerNote: 'Operational escalation from ChatorAI.',
  }),
  failed_trigger_alert: createTemplate({
    statusLabel: 'Automation Alert',
    subject: 'Automation trigger failed in {{workspace_name}}',
    preheader: 'A workflow execution failed.',
    title: 'A trigger execution failed',
    intro: 'An automation workflow failed while processing a recent event.',
    sections: [
      'Trigger: {{trigger_name}}.',
      'Error: {{error_summary}}.',
    ],
    cta: { label: 'Open Dashboard', url: '{{dashboard_link}}' },
    supportText: 'This alert was sent to the workspace operators configured for administration.',
    trustText: 'Review the workflow before the next matching event is processed.',
    footerNote: 'Automation alert from ChatorAI.',
  }),
  scheduled_report_delivery: createTemplate({
    statusLabel: 'Report',
    subject: 'Scheduled report for {{workspace_name}}',
    preheader: 'Your requested report is ready.',
    title: 'Your scheduled report is ready',
    intro: 'The latest scheduled report for {{workspace_name}} has been prepared.',
    sections: [
      'Review the report from the dashboard for the latest operational and revenue metrics.',
    ],
    cta: { label: 'Open Report', url: '{{report_link}}' },
    supportText: 'Reply to this email or contact {{support_email}}.',
    trustText: 'This report was generated automatically from your configured schedule.',
    footerNote: 'Scheduled report delivery.',
  }),
  vip_lead_alert: createTemplate({
    statusLabel: 'VIP Lead',
    subject: 'VIP lead detected in {{workspace_name}}',
    preheader: 'A priority lead needs immediate attention.',
    title: 'VIP lead alert',
    intro: 'A priority lead has been detected and flagged for immediate follow-up.',
    sections: [
      'Lead: {{customer_name}}.',
      'Score: {{lead_score}}.',
      'Channel: {{channel_name}}.',
    ],
    cta: { label: 'Open Conversation', url: '{{conversation_link}}' },
    supportText: 'This alert was sent to operators responsible for revenue follow-up.',
    trustText: 'Move quickly while buyer intent is high.',
    footerNote: 'Revenue alert from ChatorAI.',
  }),
  high_value_opportunity_alert: createTemplate({
    statusLabel: 'Revenue Alert',
    subject: 'High-value opportunity detected in {{workspace_name}}',
    preheader: 'A significant deal requires attention.',
    title: 'High-value opportunity alert',
    intro: 'A high-value deal has been created or updated and needs review.',
    sections: [
      'Customer: {{customer_name}}.',
      'Estimated value: {{estimated_value}} {{currency}}.',
    ],
    cta: { label: 'Open Conversation', url: '{{conversation_link}}' },
    supportText: 'This alert was sent to workspace operators with revenue responsibility.',
    trustText: 'Review the deal quickly to keep the opportunity moving.',
    footerNote: 'Revenue alert from ChatorAI.',
  }),
};

function getEmailTemplate(templateName) {
  const key = String(templateName || '').trim();
  const template = templates[key];
  if (!template) {
    const err = new Error(`Unknown email template: ${templateName || ''}`);
    err.code = 'EMAIL_TEMPLATE_NOT_FOUND';
    err.status = 400;
    throw err;
  }
  return template;
}

function listEmailTemplates() {
  return Object.keys(templates);
}

module.exports = {
  getEmailTemplate,
  listEmailTemplates,
};
